money order

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -376,26 +376,6 @@ jobs:
           ulimit -c unlimited
           ctest --timeout 300 -j$(nproc) --output-on-failure -LE performance
         working-directory: build
-      - name: Check manifest
-        id: check_manifest
-        working-directory: build
-        run: |
-          sed -i 's|nifi\.extension\.path=\.\./extensions/\*|nifi.extension.path=./*|' conf/minifi.properties
-          ./bin/minifi --manifest | diff -u ../.github/references/ubuntu_22_04_clang_arm_manifest.json - > manifest.patch || {
-            echo "::error::Manifest mismatch! Download the artifact to apply the patch."
-            cat manifest.patch
-            exit 1
-          }
-
-      - name: Upload patch file
-        if: failure() && steps.check_manifest.outcome == 'failure'
-        uses: actions/upload-artifact@v4
-        with:
-          name: update-manifest.patch
-          path: build/manifest.patch
-          if-no-files-found: ignore
-          retention-days: 5
-
       - name: performance-test
         id: performance-test
         run: ctest -j1 --verbose -L performance
@@ -558,6 +538,39 @@ jobs:
         with:
           name: minifi_docker
           path: build/minifi_docker.tar
+  check_manifest:
+    name: "Check manifest (x86_64)"
+    needs: docker_build
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - id: checkout
+        uses: actions/checkout@v6
+      - name: Download artifact
+        uses: actions/download-artifact@v8
+        with:
+          name: minifi_docker
+          path: build
+      - name: Load Docker image
+        run: docker load --input ./build/minifi_docker.tar | awk '{print $NF}' | xargs -I {} docker tag {} apacheminificpp:manifest
+      - name: Check manifest
+        id: check_manifest
+        run: |
+          docker run --rm apacheminificpp:manifest ./bin/minifi --manifest > manifest.json
+          diff -u --label a/.github/references/docker_manifest.json --label b/.github/references/docker_manifest.json \
+            .github/references/docker_manifest.json manifest.json > manifest.patch || {
+            echo "::error::Manifest mismatch! Download the update-manifest.patch artifact and apply it with 'git apply manifest.patch'."
+            head -n 200 manifest.patch
+            exit 1
+          }
+      - name: Upload patch file
+        if: failure() && steps.check_manifest.outcome == 'failure'
+        uses: actions/upload-artifact@v7
+        with:
+          name: update-manifest.patch
+          path: manifest.patch
+          if-no-files-found: ignore
+          retention-days: 5
   modular_docker_tests:
     name: "Modular Docker integration tests (x86_64)"
     needs: docker_build
